# Generated by Django 3.2.3 on 2021-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='user_solver',
            field=models.TextField(default=''),
        ),
    ]
