# Generated by Django 3.2.3 on 2021-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_user_solver'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='user_solver',
            field=models.TextField(default=''),
        ),
    ]
