# Generated by Django 3.2.3 on 2021-05-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_theme_user_solver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='user_solver',
        ),
    ]
